import { Readable } from "node:stream";
import { objectStorageClient } from "./objectStorage";

/**
 * Object-storage adapter for assistant-generated exports (Task #684).
 *
 * Each `assistant_exports` row stores only metadata + a `storage_key`
 * pointing at the actual bytes in App Storage. This module is the
 * single seam responsible for writing / reading / deleting those bytes
 * so the rest of the codebase (export tools, download route, hourly
 * cleanup scheduler) never imports the GCS client directly — making
 * it trivial to mock in tests with `vi.mock`.
 */

function parseObjectPath(path: string): {
  bucketName: string;
  objectName: string;
} {
  const p = path.startsWith("/") ? path : `/${path}`;
  const parts = p.split("/");
  if (parts.length < 3) {
    throw new Error("Invalid object storage path: " + path);
  }
  return {
    bucketName: parts[1],
    objectName: parts.slice(2).join("/"),
  };
}

/**
 * Build the canonical storage key for a given export id. We namespace
 * exports under `assistant-exports/` inside the configured private dir
 * so they're easy to identify and prune separately from user uploads.
 */
export function assistantExportStorageKey(exportId: string): string {
  const dir = process.env.PRIVATE_OBJECT_DIR;
  if (!dir) {
    throw new Error(
      "PRIVATE_OBJECT_DIR not set — required to persist assistant exports.",
    );
  }
  const base = dir.endsWith("/") ? dir.slice(0, -1) : dir;
  return `${base}/assistant-exports/${exportId}`;
}

/** Upload the generated bytes for an export. Returns the storage key. */
export async function putAssistantExportObject(
  exportId: string,
  content: Buffer,
  contentType: string,
): Promise<string> {
  const key = assistantExportStorageKey(exportId);
  const { bucketName, objectName } = parseObjectPath(key);
  const file = objectStorageClient.bucket(bucketName).file(objectName);
  await file.save(content, {
    contentType,
    resumable: false,
  });
  return key;
}

/**
 * Open a read stream for a previously-stored export. `size` reflects
 * the object's stored length when available — used to set
 * `Content-Length` on the download response. Throws if the object is
 * missing (the caller surfaces this as a 404/410 to the operator).
 */
export async function getAssistantExportObjectStream(
  storageKey: string,
): Promise<{ stream: Readable; size: number | null }> {
  const { bucketName, objectName } = parseObjectPath(storageKey);
  const file = objectStorageClient.bucket(bucketName).file(objectName);
  const [metadata] = await file.getMetadata();
  const size = metadata.size != null ? Number(metadata.size) : null;
  return {
    stream: file.createReadStream(),
    size: Number.isFinite(size) ? size : null,
  };
}

/**
 * Best-effort delete of a previously-stored export. Swallows
 * "not found" so the hourly cleanup scheduler can re-run without
 * issue if a previous pass already deleted the object.
 */
export async function deleteAssistantExportObject(
  storageKey: string,
): Promise<void> {
  const { bucketName, objectName } = parseObjectPath(storageKey);
  const file = objectStorageClient.bucket(bucketName).file(objectName);
  await file.delete({ ignoreNotFound: true });
}
