import { Router, type IRouter } from "express";
import healthRouter from "./health";
import configRouter from "./config";
import resetRouter from "./reset";
import adminBackupRouter from "./admin-backup";
import importRouter from "./import";
import customersRouter from "./customers";
import propertiesRouter from "./properties";
import buildingsRouter from "./buildings";
import leasesRouter from "./leases";
import leasesImportPdfRouter from "./leases-import-pdf";
import sharepointLeasesRouter from "./sharepoint-leases";
import leasesImportMasterRouter from "./leases-import-master";
import roomNightLogsRouter from "./room-night-logs";
import insuranceCertificatesRouter from "./insurance-certificates";
import propertyViolationsRouter from "./property-violations";
import projectedMoveInsRouter from "./projected-move-ins";
import roomsRouter from "./rooms";
import bedsRouter from "./beds";
import bedWeeklyRatesRouter from "./bed-weekly-rates";
import occupantsRouter from "./occupants";
import occupantsImportXlsxRouter from "./occupants-import-xlsx";
import rosterRouter from "./roster";
import utilitiesRouter from "./utilities";
import otherCostsRouter from "./other-costs";
import payrollRouter from "./payroll";
import payrollImportDeductionsRouter from "./payroll-import-deductions";
import payrollSyncZenopleRouter from "./payroll-sync-zenople";
import payrollDeductionsRouter from "./payroll-deductions";
import zenopleMatchRouter from "./zenople-match";
import financeRouter from "./finance";
import financePeriodRouter from "./finance-period";
import bedsMoveRouter from "./beds-move";
import occupantMoveOutRouter from "./occupant-move-out";
import attentionRouter from "./attention";
import searchRouter from "./search";
import propertiesFromLeaseRouter from "./properties-from-lease";
import attachedAssetsRouter from "./attached-assets";
import leaseDigestRouter from "./lease-digest";
import digestRecipientsRouter from "./digest-recipients";
import storageRouter from "./storage";
import teamRouter from "./team";
import activityRouter from "./activity";
import assistantRouter from "./assistant";
import qboRouter from "./qbo";
import qboMappingRulesRouter from "./qbo-mapping-rules";
import reconciliationRouter from "./reconciliation";
import vehiclesRouter from "./vehicles";
import vehicleRidersRouter from "./vehicle-riders";
import vehicleFuelChargesRouter from "./vehicle-fuel-charges";
import vehicleMaintenanceRouter from "./vehicle-maintenance";
import vehicleLeasesRouter from "./vehicle-leases";
import vehicleInsuranceRouter from "./vehicle-insurance";

const router: IRouter = Router();

router.use(healthRouter);
router.use(configRouter);
router.use(storageRouter);
router.use(resetRouter);
router.use(adminBackupRouter);
router.use(importRouter);
router.use(customersRouter);
router.use(propertiesRouter);
router.use(buildingsRouter);
router.use(leasesRouter);
router.use(leasesImportPdfRouter);
router.use(sharepointLeasesRouter);
router.use(leasesImportMasterRouter);
router.use(roomNightLogsRouter);
router.use(insuranceCertificatesRouter);
router.use(propertyViolationsRouter);
router.use(projectedMoveInsRouter);
router.use(roomsRouter);
router.use(bedsRouter);
router.use(bedWeeklyRatesRouter);
router.use(occupantsRouter);
router.use(occupantsImportXlsxRouter);
router.use(rosterRouter);
router.use(utilitiesRouter);
router.use(otherCostsRouter);
router.use(payrollRouter);
router.use(payrollImportDeductionsRouter);
router.use(payrollSyncZenopleRouter);
router.use(payrollDeductionsRouter);
router.use(zenopleMatchRouter);
router.use(financeRouter);
router.use(financePeriodRouter);
router.use(bedsMoveRouter);
router.use(occupantMoveOutRouter);
router.use(attentionRouter);
router.use(searchRouter);
router.use(propertiesFromLeaseRouter);
router.use(attachedAssetsRouter);
router.use(leaseDigestRouter);
router.use(digestRecipientsRouter);
router.use(teamRouter);
router.use(activityRouter);
router.use(qboRouter);
router.use(qboMappingRulesRouter);
router.use(reconciliationRouter);
router.use(vehiclesRouter);
router.use(vehicleRidersRouter);
router.use(vehicleFuelChargesRouter);
router.use(vehicleMaintenanceRouter);
router.use(vehicleLeasesRouter);
router.use(vehicleInsuranceRouter);
router.use(assistantRouter);

export default router;
