import { Router, type IRouter } from "express";
import healthRouter from "./health";
import configRouter from "./config";
import resetRouter from "./reset";
import importRouter from "./import";
import customersRouter from "./customers";
import propertiesRouter from "./properties";
import buildingsRouter from "./buildings";
import leasesRouter from "./leases";
import leasesImportPdfRouter from "./leases-import-pdf";
import leasesImportMasterRouter from "./leases-import-master";
import roomNightLogsRouter from "./room-night-logs";
import insuranceCertificatesRouter from "./insurance-certificates";
import propertyViolationsRouter from "./property-violations";
import projectedMoveInsRouter from "./projected-move-ins";
import roomsRouter from "./rooms";
import bedsRouter from "./beds";
import occupantsRouter from "./occupants";
import utilitiesRouter from "./utilities";
import otherCostsRouter from "./other-costs";
import payrollRouter from "./payroll";
import payrollDeductionsRouter from "./payroll-deductions";
import attachedAssetsRouter from "./attached-assets";
import leaseDigestRouter from "./lease-digest";
import digestRecipientsRouter from "./digest-recipients";
import storageRouter from "./storage";

const router: IRouter = Router();

router.use(healthRouter);
router.use(configRouter);
router.use(storageRouter);
router.use(resetRouter);
router.use(importRouter);
router.use(customersRouter);
router.use(propertiesRouter);
router.use(buildingsRouter);
router.use(leasesRouter);
router.use(leasesImportPdfRouter);
router.use(leasesImportMasterRouter);
router.use(roomNightLogsRouter);
router.use(insuranceCertificatesRouter);
router.use(propertyViolationsRouter);
router.use(projectedMoveInsRouter);
router.use(roomsRouter);
router.use(bedsRouter);
router.use(occupantsRouter);
router.use(utilitiesRouter);
router.use(otherCostsRouter);
router.use(payrollRouter);
router.use(payrollDeductionsRouter);
router.use(attachedAssetsRouter);
router.use(leaseDigestRouter);
router.use(digestRecipientsRouter);

export default router;
