// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ho-architectural-dark/Dashboard.tsx": () => import("../components/mockups/ho-architectural-dark/Dashboard.tsx"),
  "./components/mockups/ho-architectural-dark/Properties.tsx": () => import("../components/mockups/ho-architectural-dark/Properties.tsx"),
  "./components/mockups/ho-architectural-dark/PropertyDetail.tsx": () => import("../components/mockups/ho-architectural-dark/PropertyDetail.tsx"),
  "./components/mockups/ho-architectural-dark/Shared.tsx": () => import("../components/mockups/ho-architectural-dark/Shared.tsx"),
  "./components/mockups/ho-architectural-dark/SystemKit.tsx": () => import("../components/mockups/ho-architectural-dark/SystemKit.tsx"),
  "./components/mockups/ho-editorial-brief/Dashboard.tsx": () => import("../components/mockups/ho-editorial-brief/Dashboard.tsx"),
  "./components/mockups/ho-editorial-brief/Properties.tsx": () => import("../components/mockups/ho-editorial-brief/Properties.tsx"),
  "./components/mockups/ho-editorial-brief/PropertyDetail.tsx": () => import("../components/mockups/ho-editorial-brief/PropertyDetail.tsx"),
  "./components/mockups/ho-editorial-brief/Shared.tsx": () => import("../components/mockups/ho-editorial-brief/Shared.tsx"),
  "./components/mockups/ho-editorial-brief/SystemKit.tsx": () => import("../components/mockups/ho-editorial-brief/SystemKit.tsx"),
  "./components/mockups/ho-operator-console/Dashboard.tsx": () => import("../components/mockups/ho-operator-console/Dashboard.tsx"),
  "./components/mockups/ho-operator-console/Properties.tsx": () => import("../components/mockups/ho-operator-console/Properties.tsx"),
  "./components/mockups/ho-operator-console/PropertyDetail.tsx": () => import("../components/mockups/ho-operator-console/PropertyDetail.tsx"),
  "./components/mockups/ho-operator-console/SystemKit.tsx": () => import("../components/mockups/ho-operator-console/SystemKit.tsx"),
  "./components/mockups/ho-spatial-board/Dashboard.tsx": () => import("../components/mockups/ho-spatial-board/Dashboard.tsx"),
  "./components/mockups/ho-spatial-board/Properties.tsx": () => import("../components/mockups/ho-spatial-board/Properties.tsx"),
  "./components/mockups/ho-spatial-board/PropertyDetail.tsx": () => import("../components/mockups/ho-spatial-board/PropertyDetail.tsx"),
  "./components/mockups/ho-spatial-board/Shared.tsx": () => import("../components/mockups/ho-spatial-board/Shared.tsx"),
  "./components/mockups/ho-spatial-board/SystemKit.tsx": () => import("../components/mockups/ho-spatial-board/SystemKit.tsx")
};
